### ISSUE TITLE
Sending arbitrary audio to WebRTC

### ISSUE THREAD

**Issue by mikeal** [cwilso/WebAudio#15]
Hey cwilso,

Sorry for posting a general audio question here but you're probably the only person who knows how to do this.

I have some audio elements, effects, and a microphone from getUserMedia, and I'd like to send all of this output to WebRTC and to MediaRecorder.

The problem is that I can't find any documentation on creating MediaStream objects and sending data to them, all the MediaStreams I can find come from some pre-existing source.

Hope you can help, and thanks in advance :)

**Comment by RationalCoding** [comment]
@mikeal Once you get a MediaStream object from getUserMedia, just create an AudioContext with a MediaStreamSource and MediaStreamOutput.

```javascript
// call getUserMedia to get a MediaStream "stream"

var ctx = new AudioContext()

var inputNode = ctx.createMediaStreamSource(stream)
var outputNode = ctx.createMediaStream.createMediaStreamDestination()

inputNode.connect(outputNode) // You could connect them through any other nodes

outputNode.stream // Your output MediaStream to be sent over WebRTC or pass to MediaRecorder
```

I know it's probably too late, but maybe others will find this useful.

**Comment by mikeal** [comment]
It's actually a little trickier than that for several different use cases, and there's also a couple bugs you have have to work around.

I ended up writing this library to deal with it all https://github.com/mikeal/waudio/blob/master/index.js
